"""Build Obsidian vault from graphify graph.json"""
import json, os, pathlib, shutil
from collections import defaultdict

vault = pathlib.Path(os.path.expanduser("~")) / "Documents" / "Obsidian Vault" / "ufs-newsletter"
vault.mkdir(parents=True, exist_ok=True)
(vault / "sources").mkdir(exist_ok=True)
(vault / "architecture").mkdir(exist_ok=True)

BASE = pathlib.Path(r"c:\Users\venky\Desktop\ufs\New folder\ufs-newsletter")
GRAPH = BASE / "api" / "graphify-out" / "graph.json"

with open(GRAPH, encoding="utf-8") as f:
    g = json.load(f)

nodes = {n["id"]: n for n in g["nodes"]}
links = g["links"]

adj = defaultdict(list)
for lk in links:
    adj[lk.get("source", "")].append((lk.get("relation", ""), lk.get("target", "")))

communities = defaultdict(list)
for nid, n in nodes.items():
    communities[n.get("community", 0)].append(n)

# ── index.md ──────────────────────────────────────────────
index_lines = [
    "# UFS Newsletter — Knowledge Graph",
    "",
    "> Generated by graphify v4 from the `api/` codebase.",
    "> 220 nodes · 448 edges · 28 communities",
    "",
    "## Architecture at a Glance",
    "",
    "| Layer | Key Files |",
    "|-------|-----------|",
    "| Data Sources | `grok_source`, `reddit_source`, `news_api_source`, `foreclosure_scraper`, `zillow_source`, `housingwire_source`, `mortgagepoint_source`, `redfin_source`, `fred_source`, `fdic_source`, `homesteps_source` |",
    "| Aggregator | `data_aggregator.py` — runs all sources, feeds sections |",
    "| AI Drafting | `ai_drafter.py` — OpenAI GPT-4 per newsletter section |",
    "| Email | `mailchimp_client.py`, `email_notifier.py` |",
    "| API Routes | `pipeline.py`, `drafts.py`, `newsletter.py`, `articles.py`, `sources.py` |",
    "| Models | `newsletter.py`, `draft.py`, `article.py`, `approval_log.py` |",
    "",
    "## God Nodes (Most Connected Abstractions)",
    "",
    "| Node | Edges | Role |",
    "|------|-------|------|",
    "| `SourceResult` | 43 | Return type for every data collector |",
    "| `BaseSource` | 40 | Abstract base — all 11 sources extend this |",
    "| `Draft` | 15 | Core model holding raw data + AI draft + human edits |",
    "| `Article` | 13 | Published newsletter article record |",
    "",
    "## Communities",
    "",
]
for cid in sorted(communities.keys()):
    cnodes = communities[cid]
    labels = [n.get("label", "") for n in cnodes[:3]]
    index_lines.append(
        f"- [[architecture/Community_{cid}|Community {cid}]] ({len(cnodes)} nodes) — {' · '.join(labels)}"
    )

index_lines += [
    "",
    "## Data Source Notes",
    "",
    "- [[sources/grok_source|Grok / X API]]",
    "- [[sources/reddit_source|Reddit]]",
    "- [[sources/news_api_source|News API]]",
    "- [[sources/foreclosure_scraper|Foreclosure.com Scraper]]",
    "- [[sources/zillow_source|Zillow RSS + Listings]]",
    "- [[sources/housingwire_source|HousingWire RSS]] ✨ new",
    "- [[sources/mortgagepoint_source|The MortgagePoint RSS]] ✨ new",
    "- [[sources/redfin_source|Redfin S3 Market Data]] ✨ new",
    "- [[sources/fred_source|FRED API]] ✨ new",
    "- [[sources/fdic_source|FDIC BankFind API]] ✨ new",
    "- [[sources/homesteps_source|Freddie Mac HomeSteps]] ✨ new",
    "",
    "---",
    "_See [[GRAPH_REPORT]] for full community analysis._",
]
(vault / "index.md").write_text("\n".join(index_lines), encoding="utf-8")
print("wrote index.md")

# ── Community notes ───────────────────────────────────────
for cid in sorted(communities.keys()):
    cnodes = communities[cid]
    lines = [f"# Community {cid}", "", f"**{len(cnodes)} nodes**", "", "## Members", ""]
    for n in cnodes:
        lines.append(f"- `{n.get('label', '')}` — {n.get('source_file', '')}:{n.get('source_location', '')}")
    ext = [
        (rel, tgt) for nid in [n["id"] for n in cnodes]
        for rel, tgt in adj.get(nid, [])
        if nodes.get(tgt, {}).get("community") != cid
    ][:10]
    if ext:
        lines += ["", "## External Connections", ""]
        for rel, tgt in ext:
            lines.append(f"- `{nodes.get(tgt, {}).get('label', tgt)}` via `{rel}`")
    (vault / "architecture" / f"Community_{cid}.md").write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {len(communities)} community notes")

# ── Source notes ──────────────────────────────────────────
SOURCE_META = {
    "grok_source": ("Grok / X API", "GrokSource", "Pulls recent X posts about REO via Grok API.", "GROK_API_KEY", "industry_news"),
    "reddit_source": ("Reddit", "RedditSource", "Top weekly posts from r/realestate and r/RealEstateInvesting.", "Optional", "industry_news"),
    "news_api_source": ("News API", "NewsApiSource", "REO/foreclosure news articles from newsapi.org.", "NEWS_API_KEY", "industry_news"),
    "foreclosure_scraper": ("Foreclosure.com", "ForeclosureScraper", "State listing counts — often blocked (403).", "Cookie optional", "market_pulse, hot_markets"),
    "zillow_source": ("Zillow", "ZillowResearchSource + ZillowListingSource", "Zillow RSS feeds + listing pages.", "Cookie optional", "industry_news, market_pulse"),
    "housingwire_source": ("HousingWire RSS ✨", "HousingWireSource", "Industry news RSS — always live, no auth. 10 articles/day.", "None", "industry_news"),
    "mortgagepoint_source": ("The MortgagePoint RSS ✨", "MortgagePointSource", "Most REO-specific trade publication. Formerly DS News.", "None", "industry_news"),
    "redfin_source": ("Redfin S3 Market Data ✨", "RedfinMarketSource", "Free weekly state + county market data. Distress score ranking.", "None", "market_pulse, hot_markets"),
    "fred_source": ("FRED API ✨", "FredSource", "Fed delinquency rates + mortgage rates + housing starts.", "FRED_API_KEY (free)", "market_pulse"),
    "fdic_source": ("FDIC BankFind ✨", "FdicSource", "Bank failures + $500M+ bank financials. No auth.", "None", "top_banks"),
    "homesteps_source": ("Freddie Mac HomeSteps ✨", "HomeStepsSource", "Freddie Mac REO portal. HTTP 200 tested.", "None", "top_banks"),
}

for key, (name, cls, desc, auth, section) in SOURCE_META.items():
    lines = [
        f"# {name}",
        "",
        f"**Class:** `{cls}`  ",
        f"**File:** `api/services/sources/{key}.py`  ",
        f"**Auth:** `{auth}`  ",
        f"**Newsletter Section:** `{section}`",
        "",
        "## Description",
        "",
        desc,
        "",
        "## Relationships",
        "",
        "- Extends [[BaseSource]]",
        "- Returns [[SourceResult]]",
        "- Registered in [[data_aggregator]]",
        "",
        "#source #data-pipeline",
    ]
    (vault / "sources" / f"{key}.md").write_text("\n".join(lines), encoding="utf-8")
print("wrote 11 source notes")

# ── Copy graph report ─────────────────────────────────────
shutil.copy(str(GRAPH.parent / "GRAPH_REPORT.md"), str(vault / "GRAPH_REPORT.md"))

# ── Obsidian config ───────────────────────────────────────
obsidian_dir = vault / ".obsidian"
obsidian_dir.mkdir(exist_ok=True)
(obsidian_dir / "app.json").write_text('{"defaultViewMode":"source","livePreview":true}', encoding="utf-8")

print(f"\nObsidian vault ready: {vault}")
print("Open Obsidian -> File -> Open Vault -> browse to that path")
