const textEncoder = new TextEncoder();

async function signValue(value: string, secret: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    "raw",
    textEncoder.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const signature = await crypto.subtle.sign("HMAC", key, textEncoder.encode(value));
  return Array.from(new Uint8Array(signature))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

function constantTimeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let mismatch = 0;
  for (let i = 0; i < a.length; i++) {
    mismatch |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return mismatch === 0;
}

// Token format: `${userId}|${expiresAtMs}|${hmacHex}`
// Generated by clients-unitedffs using the shared INSIGHTS_SSO_SECRET
export async function verifySsoToken(token: string): Promise<boolean> {
  const secret = process.env.INSIGHTS_SSO_SECRET;
  if (!secret || !token) return false;

  const parts = token.split("|");
  if (parts.length !== 3) return false;

  const [userId, expiresAtRaw, signature] = parts;
  const expiresAt = Number.parseInt(expiresAtRaw, 10);
  if (Number.isNaN(expiresAt) || expiresAt <= Date.now()) return false;
  if (!userId) return false;

  const payload = `${userId}|${expiresAtRaw}`;
  const expectedSignature = await signValue(payload, secret);
  return constantTimeEqual(signature, expectedSignature);
}
